# Generated by Django 4.0.3 on 2022-04-11 16:47

import blog.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя автора')),
                ('image', models.ImageField(upload_to=blog.functions.user_directory_path_for_image_avatar_author_files, verbose_name='Аватар автора')),
                ('about_text', models.TextField(verbose_name='Кратко об авторе')),
                ('country', models.CharField(max_length=100, verbose_name='Страна, в которой проживает автор')),
                ('twitter_share', models.URLField(blank=True, null=True, verbose_name='Twitter автора')),
                ('facebook_share', models.URLField(blank=True, null=True, verbose_name='Facebook автора')),
                ('google_plus_share', models.URLField(blank=True, null=True, verbose_name='Google Plus автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('pk',),
                'default_related_name': 'author',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('prew', models.TextField(verbose_name='Превью поста')),
                ('image_prew', models.ImageField(blank=True, null=True, upload_to=blog.functions.user_directory_path_for_image_preview_post_files, verbose_name='Картинка для поста')),
                ('create_post_date', models.DateField(auto_now=True, verbose_name='Дата создания поста')),
                ('last_edit_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последнего изменения поста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('create_post_date',),
            },
        ),
    ]
