# Generated by Django 4.0.3 on 2022-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_post_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения поста'),
        ),
    ]
